/*
* SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
* SPDX-License-Identifier: Apache-2.0
*/
#version 450
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_explicit_arithmetic_types_int16 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) buffer AliasBuffer
{
    uint16_t values[];
};

void main()
{
    uint index = gl_GlobalInvocationID.x + (gl_GlobalInvocationID.y * 16u);
    values[index] = uint16_t(index + 5u);
}
