#
# SPDX-FileCopyrightText: Copyright 2022-2025 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#
[tool.black]
target-version = ['py310']

[tool.pytest.ini_options]
markers = [
    "shaders",
    "pipeline_cache",
    "mark_boundary",
    "tensor_aliasing",
    "memory_aliasing",
    "dds",
    "barrier",
    "mipmaps_writing",
    "vgf_graph",
    "vgf_shader",
    "tiling",
    "spec_const",
]
