// SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
// SPDX-License-Identifier: Apache-2.0
#version 460

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) readonly uniform image2D inputImage;
layout(set = 0, binding = 1, rgba8) writeonly uniform image2D outputImage;

void main() {
    const ivec2 outputPosition = ivec2(gl_GlobalInvocationID.xy);
    const ivec2 outputSize = imageSize(outputImage);
    if (any(greaterThanEqual(outputPosition, outputSize))) {
        return;
    }
    const ivec2 inputSize = imageSize(inputImage);
    imageStore(outputImage, outputPosition, imageLoad(inputImage, outputPosition % inputSize));
}
