/*
* SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
* SPDX-License-Identifier: Apache-2.0
*/
#extension GL_EXT_shader_explicit_arithmetic_types_int8 : require

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

// Use non-sequential binding numbers to make descriptor matching explicit.
layout(set = 0, binding = 4) buffer in1 { TestType In1Buffer[10]; };
layout(set = 0, binding = 9) buffer in2 { TestType In2Buffer[10]; };
layout(set = 1, binding = 17) buffer out1 { TestType OutBuffer[10]; };

void main()
{
    OutBuffer[gl_GlobalInvocationID.x] = In1Buffer[gl_GlobalInvocationID.x] + In2Buffer[gl_GlobalInvocationID.x];
}
